# Generated by Django 3.2.8 on 2021-10-18 19:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(default='', max_length=100, verbose_name='Province ')),
                ('city', models.CharField(default='', max_length=100, verbose_name='city')),
                ('district', models.CharField(default='', max_length=100, verbose_name='Area ')),
                ('address', models.CharField(default='', max_length=100, verbose_name='Address')),
                ('signer_name', models.CharField(default='', max_length=100, verbose_name='Signee ')),
                ('signer_mobile', models.CharField(default='', max_length=11, verbose_name='Phone ')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='add time')),
            ],
            options={
                'verbose_name': 'Shipping address',
                'verbose_name_plural': 'Shipping address',
            },
        ),
        migrations.CreateModel(
            name='UserFav',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='add time')),
            ],
            options={
                'verbose_name': 'User Collection',
                'verbose_name_plural': 'User Collection',
            },
        ),
        migrations.CreateModel(
            name='UserLeavingMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.IntegerField(choices=[(1, 'leave a message'), (2, 'Complaint'), (3, 'ask'), (4, 'After Sales'), (5, 'Buy')], default=1, help_text='Message type: 1 (message), 2 (complaint), 3 (inquiry), 4 (after sale), 5 (buy)', verbose_name='Message Type')),
                ('subject', models.CharField(default='', max_length=100, verbose_name='Theme ')),
                ('message', models.TextField(default='', help_text='Message content', verbose_name='Message content')),
                ('file', models.FileField(help_text='Uploaded file', upload_to='message/images/', verbose_name='Uploaded file')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='add time')),
            ],
            options={
                'verbose_name': 'User Comments',
                'verbose_name_plural': 'User Comments',
            },
        ),
    ]
