# Generated by Django 3.2.8 on 2021-10-18 19:30

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderGoods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_num', models.IntegerField(default=0, verbose_name='Number of Products')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='add time')),
            ],
            options={
                'verbose_name': 'Order Goods',
                'verbose_name_plural': 'Order Goods',
            },
        ),
        migrations.CreateModel(
            name='OrderInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_sn', models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='order number')),
                ('trade_no', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Transaction Number')),
                ('pay_status', models.CharField(choices=[('TRADE_SUCCESS', 'success'), ('TRADE_CLOSED', 'Timeout closed'), ('WAIT_BUYER_PAY', 'Transaction Creation'), ('TRADE_FINISHED', 'End of transaction'), ('paying', 'To be paid')], default='paying', max_length=30, verbose_name='Order Status')),
                ('post_script', models.CharField(max_length=200, verbose_name='Order Message')),
                ('order_mount', models.FloatField(default=0.0, verbose_name='order amount')),
                ('pay_time', models.DateTimeField(blank=True, null=True, verbose_name='Payment time')),
                ('address', models.CharField(default='', max_length=100, verbose_name='Shipping address')),
                ('signer_name', models.CharField(default='', max_length=20, verbose_name='Signee ')),
                ('singer_mobile', models.CharField(max_length=11, verbose_name='contact number')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='add time')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Order',
            },
        ),
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nums', models.IntegerField(default=0, verbose_name='Purchase quantity')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='add time')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.goods', verbose_name='commodity')),
            ],
            options={
                'verbose_name': 'shopping cart',
                'verbose_name_plural': 'shopping cart',
            },
        ),
    ]
