# Generated by Django 3.2.8 on 2021-10-18 19:30

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_sn', models.CharField(default='', max_length=50, verbose_name='Commodity unique article number ')),
                ('name', models.CharField(max_length=100, verbose_name='Product name')),
                ('click_num', models.IntegerField(default=0, verbose_name='Clicks')),
                ('sold_num', models.IntegerField(default=0, verbose_name='Commodity Sales')),
                ('fav_num', models.IntegerField(default=0, verbose_name='Number of Favorites')),
                ('goods_num', models.IntegerField(default=0, verbose_name='Inventory')),
                ('market_price', models.FloatField(default=0, verbose_name='market price')),
                ('shop_price', models.FloatField(default=0, verbose_name='Our shop price')),
                ('goods_brief', models.TextField(max_length=500, verbose_name='Short description of the product')),
                ('ship_free', models.BooleanField(default=True, verbose_name='Whether to bear freight')),
                ('goods_front_image', models.ImageField(blank=True, null=True, upload_to='goods/images/', verbose_name='cover picture')),
                ('is_new', models.BooleanField(default=False, verbose_name='Is it new?')),
                ('is_hot', models.BooleanField(default=False, verbose_name='Whether it sells well')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='add time')),
            ],
            options={
                'verbose_name': 'commodity',
                'verbose_name_plural': 'commodity',
            },
        ),
        migrations.CreateModel(
            name='GoodsCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', help_text='Category name ', max_length=30, verbose_name='Category name')),
                ('code', models.CharField(default='', help_text='Category code ', max_length=30, verbose_name='Category code')),
                ('desc', models.TextField(default='', help_text='Category description ', verbose_name='Category description')),
                ('category_type', models.IntegerField(choices=[(1, 'First Class'), (2, 'Class 2'), (3, 'Three-level category')], help_text='Category level', verbose_name='Category level')),
                ('is_tab', models.BooleanField(default=False, help_text='Whether to navigate', verbose_name='Whether to navigate')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='add time')),
                ('parent_category', models.ForeignKey(blank=True, help_text='Parent Directory', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_cat', to='goods.goodscategory', verbose_name='Parent Category Level')),
            ],
            options={
                'verbose_name': 'Commodity Category',
                'verbose_name_plural': 'Commodity Category',
            },
        ),
        migrations.CreateModel(
            name='HotSearchWords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keywords', models.CharField(default='', max_length=20, verbose_name='Hot Words ')),
                ('index', models.IntegerField(default=0, verbose_name='Sort')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='add time')),
            ],
            options={
                'verbose_name': 'Hot word search',
                'verbose_name_plural': 'Hot word search',
            },
        ),
        migrations.CreateModel(
            name='IndexAd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='goods.goodscategory', verbose_name='Commodity Category')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goods', to='goods.goods')),
            ],
            options={
                'verbose_name': 'Home Product Category Advertisement',
                'verbose_name_plural': 'Home Product Category Advertisement',
            },
        ),
        migrations.CreateModel(
            name='GoodsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Picture ')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='add time')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='goods.goods', verbose_name='commodity')),
            ],
            options={
                'verbose_name': 'product picture',
                'verbose_name_plural': 'product picture',
            },
        ),
        migrations.CreateModel(
            name='GoodsCategoryBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', help_text='Brand name ', max_length=30, verbose_name='Brand name')),
                ('desc', models.TextField(default='', help_text='Brand description ', max_length=200, verbose_name='Brand description')),
                ('image', models.ImageField(max_length=200, upload_to='brands/')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='add time')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brands', to='goods.goodscategory', verbose_name='Commodity Category')),
            ],
            options={
                'verbose_name': 'Brand',
                'verbose_name_plural': 'Brand',
                'db_table': 'goods_goodsbrand',
            },
        ),
        migrations.AddField(
            model_name='goods',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.goodscategory', verbose_name='Commodity Category'),
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='banner', verbose_name='Carousel pictures')),
                ('index', models.IntegerField(default=0, verbose_name='Carousel Order')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='add time')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.goods', verbose_name='commodity')),
            ],
            options={
                'verbose_name': 'Carousel goods',
                'verbose_name_plural': 'Carousel goods',
            },
        ),
    ]
